#!/bin/bash
# Open files with the vim text editor based on indices

files=()
count=0

# check if no file was specified
if [ $# -eq 0 ]; then
	echo -e "\e[94mPlease specify a file or files to remove \e[33m:O\e[0m"
	exit 1
fi

# store all the files of the current directory in an array
for file in *; do
  files+=("$file")
  count=$((count+1))
done

argument=""
file_index="$1"

if [[ $file_index =~ ^[0-9]+$ ]]; then
    argument+=" ${files[$file_index]}"
else
    echo -e "\e[94mOnly file indices allowed \e[33m:(\e[0m"
	exit 1
fi

# check if the index specified is valid
if [[ $argument =~ ^[[:space:]]*$ ]]; then
  echo -e "\e[94mFile index out of range \e[33m:/\e[0m"
else
  vim $argument
fi
